### ISSUE TITLE
Missing LICENCE file

### ISSUE THREAD

**Issue by z0u** [AStox/tankbot#2]
Please consider adding a LICENCE .txt or .md file.

**Comment by AStox** [comment]
Hi Oasakfu,
I must've accidentally deleted my old license file without noticing, so thanks for bringing this to my attention. You're post also encouraged me to do some research on common, free software licenses. I ended up going with the Apache v2.0 license, but I noticed that your game uses the GPL v3 license. Is there any specific reason why you chose that license over any other similar ones?

**Comment by z0u** [comment]
Hi AStox, sorry for the slow reply.

I chose the GPL because it's a [copyleft](http://en.wikipedia.org/wiki/Copyleft) licence: not only is it free and open source, but anyone who publishes a [modified] copy of it must also release their modifications under the GPL. Kind of like the [CC BY-SA](https://creativecommons.org/licenses/by-sa/3.0/) licences.

Thanks for adding the licence file :)
